spring:
  application:
    name: order-service  # the same with com.yiqiniu.easytrans.demos.order.Constant.APPID
  datasource: # order service datasource config
    url: jdbc:mysql://localhost:3306/ez_order?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver

server: 
  port: 9090

# RIBBON用，也可以直接开启Eureka
order-service:
  ribbon:
    listOfServers: localhost:9090

wallet-service:
  ribbon:
    listOfServers: localhost:8081

easytrans:
  master:
    zk:
      zooKeeperUrl: 127.0.0.1:2181
  stringcodec:
    zk:
      zooKeeperUrl: ${easytrans.master.zk.zooKeeperUrl}
  idgen:
    trxId:
      zkSnow:
        zooKeeperUrl: ${easytrans.master.zk.zooKeeperUrl}
  log:
    database:
      logCleanEnabled: true
      logReservedDays: 14
      logCleanTime: 01:22:00
      druid:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ez_order_translog?characterEncoding=UTF-8&useSSL=false
        username: root
        password: 1234



    
      